#!/usr/bin/env bash

ROOT=${HOME}/.wtmux

[ -d "${ROOT}" ] || git clone --recursive https://github.com/wxnacy/wtmux "${ROOT}"

# 安装依赖
brew install fpp        # for tmux-fpp
# brew install urlview    # for tmux-urlview
brew install fzf        # for tmux-fzf-url
# for tmux-logging
TMUX_CACHE_HOME="${HOME}/.local/state/tmux"
[ -d "${TMUX_CACHE_HOME}" ] || mkdir -p "${TMUX_CACHE_HOME}"

echo ''
echo 'Run the following command to quickly use wtmux'
echo ''
if [[ -d ${HOME}/.tmux || -f ${HOME}/.tmux ]];then
    echo "  mv ${HOME}/.tmux ${HOME}/.tmux.old"
fi

if [[ -d ${HOME}/.tmux.conf || -f ${HOME}/.tmux.conf ]];then
    echo "  mv ${HOME}/.tmux.conf ${HOME}/.tmux.conf.old"
fi
echo "  ln -sf ${ROOT} ${HOME}/.tmux"
echo "  ln -sf ${ROOT}/tmux.conf ${HOME}/.tmux.conf"
echo ""
